Reverted:: Getting error while generating ApprovedProductRequirementsReport PDF (OFBIZ-11845)
Integration tests don't pass. Here is the error:
Recoverable error on line 145 column 98
  SXCH0003: org.apache.fop.fo.ValidationException: null:145:98: "fo:table-body"
  is not a   valid child of "fo:table-body"! (See position 145:98)

The initial "fixed" error is:
org.apache.fop.fo.ValidationException: null:88:232: "fo:table-row" is not a
valid child of "fo:table"! (See position 88:232)

Another error exists at ApprovedProductRequirementsByVendorReport:
org.apache.fop.fo.ValidationException: null:95:2: "fo:table-cell" is not a valid
child of "fo:table-cell"! (See position 95:2)

For now I'm not quite even sure how you get to
ApprovedProductRequirementsReport
When you approve a requirement it does not show at
ordermgr/control/ApprovedProductRequirements

I thought the error could be due to a missing requirementId. But using
ordermgr/control/ApprovedProductRequirementsReport?requirementId=10000
you get the same error.

It seems related to OFBIZ-6354, but could be rather an issue with
ApprovedProductRequirements screen where
<set field="genericLinkTarget" value="ApprovedProductRequirementsReport"/>
is set

Same for ApprovedProductRequirementsByVendorReport

I did not get further for now